### ISSUE TITLE
Add .travis.yml

### ISSUE THREAD

**Issue by jcdyer** [fizzstudio/fizz#1]
- Start with eslint config

**Comment by shepazu** [comment]
Include test framework

**Comment by shepazu** [comment]
Consider if we can use this plus a comment convention (maybe linked to a gh issue) to document known hacks or workarounds in the code, or places we're incurring "quick patch vs architectural refactoring". That way we can assess when it's time to refactor or optimize away from hacks, and what bits need to change.

**Comment by jcdyer** [comment]
Addressed now in #12
