### ISSUE TITLE
Establish TS foundations.

### ISSUE THREAD

**Issue by jcdyer** [fizzstudio/fizz#4]
We want to be working with Typescript.  How can we keep it low-friction?

**Comment by jcdyer** [comment]
@shepazu I think I figured out the important piece for this: The typescript compiler has an option to recompile files whenever they are updated (probably based on file modified timestamps).  Open up a terminal window, and run `tsc -w`.  Ctrl+C exits out of it.  

Then whenever you save a file in the src directory, it will compile it, and put the resulting JS in the dist directory. 

Note: tsc will also handle plain js files, so the first step in moving to TypeScript will be moving fizz.js from dist to src.  fizz.html will continue to point at dist/fizz.js.  Try it out when you have a few minutes.

**Comment by shepazu** [comment]
`-bash: tsc: command not found`

I've pulled the latest branch. Is there something I need to run or install?

**Comment by jcdyer** [comment]
$ npm install 

should cover it.

On Fri, Sep 22, 2017 at 04:04:21AM +0000, Doug Schepers wrote regarding Re: [fizzstudio/fizz] Establish TS foundations. (#4):
